# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SerBIN <- function(Y, Z, n_prov, gamma, beta) {
    .Call(`_TmpLasso_SerBIN`, Y, Z, n_prov, gamma, beta)
}

Z_max_grLasso <- function(x, r, K, m) {
    .Call(`_TmpLasso_Z_max_grLasso`, x, r, K, m)
}

Deviance <- function(Y, p) {
    .Call(`_TmpLasso_Deviance`, Y, p)
}

grp_lasso <- function(Y, Z, n_prov, gamma, beta, K0, K1, lambda_seq, lambda_early_stop, stop_dev_ratio, group_multiplier, max_iter, tol, nullDev, backtrack, bound, initial_active_group, nvar_max, group_max, trace_lambda, single_intercept, threads) {
    .Call(`_TmpLasso_grp_lasso`, Y, Z, n_prov, gamma, beta, K0, K1, lambda_seq, lambda_early_stop, stop_dev_ratio, group_multiplier, max_iter, tol, nullDev, backtrack, bound, initial_active_group, nvar_max, group_max, trace_lambda, single_intercept, threads)
}

pp_lasso <- function(Y, Z, n_prov, gamma, beta, K0, K1, lambda_seq, lambda_early_stop, stop_dev_ratio, penalized_multiplier, max_iter, tol, nullDev, backtrack, MM, bound, initial_active_var, nvar_max, trace_lambda, single_intercept, threads) {
    .Call(`_TmpLasso_pp_lasso`, Y, Z, n_prov, gamma, beta, K0, K1, lambda_seq, lambda_early_stop, stop_dev_ratio, penalized_multiplier, max_iter, tol, nullDev, backtrack, MM, bound, initial_active_var, nvar_max, trace_lambda, single_intercept, threads)
}

rcpp_hello_world <- function() {
    .Call(`_TmpLasso_rcpp_hello_world`)
}

